### ISSUE TITLE
Please Help!!!!!!!.....Hi Tejas, Could you please help me to host this app on server 

### ISSUE THREAD

**Issue by vishaldusane30** [ttejas123/Video_conf_ScreenShare#2]

**Comment by ttejas123** [comment]
This api is just to test functionality and add new if needed. So it's basically not for hosting. Also why do you want to host this api.

**Comment by ttejas123** [comment]
Here is my hoasting if you just want to see how it's working in public domain.
Link :- https://stark-brook-90706.herokuapp.com/84b7e940-b198-436a-a349-55028bc724f2

**Comment by vishaldusane30** [comment]
Link :- https://stark-brook-90706.herokuapp.com/84b7e940-b198-436a-a349-55028bc724f2

**Comment by vishaldusane30** [comment]
I want this type of hosting app like yours 
Link :- https://stark-brook-90706.herokuapp.com/84b7e940-b198-436a-a349-55028bc724f2

**Comment by ttejas123** [comment]
I can't give you, some parts of a code is confidential, because I am
devloping this for my internship, so befor handing over to them, I can't give that
part of info/code/hosting part.
